### PR TITLE
fix top menu url and some css

### PR DESCRIPTION
**Pull request by yestaro**
fix top menu and footer link and css to follow royale main website

### CODE REVIEW

**Comment by Harbs** [comment]
Thanks for this. It looks like a nice improvement.

The links should probably all simply be domain-relative links instead of hard-coded absolute links (i.e. `/features/` instead of `https://royale.apache.org/features/` or `http://royale.apache.org/features/`.

(This is something we need to do on the main site too.) Thoughts?

**Comment by yestaro** [comment]
Yes, relative links are better than absolute links.  
But main site's domain is royale.apache.org that is different from doc site's domain - apache.github.io  
I don't know how to use relative links, maybe use base tag in head.
so I just fix the link base on original code. At least let the doc site has right links.

ps: I am new to use pull request, do I need close this pull request?

**Comment by Harbs** [comment]
No. I merged the PR because it's an improvement. The relative links can always be added later.

Thanks!

**Comment by carlosrovira** [comment]
I think to get relative links in docs, we should have cloacking url to make "apache.github.io" be "royale.apache.org", don't know if this is possible :?

**Pull request merged**
