### PR TITLE
Improve Build Instructions

### PR DESCRIPTION
**Pull request by Aszusz**
This feature improves build instructions in README.md. New instructions:
- are more detailed
- show how to override default _config with local_config. It allows the user to see the correct CSS locally.

### CODE REVIEW

**Comment by carlosrovira** [comment]
Thanks for your contribution @Aszusz! You're welcome to continue improving it! Thanks :)

**Comment by Aszusz** [comment]
Thank you :) New improvements coming soon!

**Comment by aharui** [comment]
Yes, thank you @Aszusz, however these changes should go against the develop branch, not master.  @carlosrovira can you move that commit?

**Comment by Aszusz** [comment]
@aharui Thank you, next PRs will be against develop

**Comment by piotrzarzycki21** [comment]
@aharui can we make cherry pick from master to develop and revert on master?

**Comment by aharui** [comment]
I don't know the best way.

**Comment by Aszusz** [comment]
@aharui @carlosrovira Excuse me guys, but I've just checked out develop and it seems like it's 1 year old. It doesn't even contain the section I modified. Should I continue to work against master?

**Comment by joshtynjala** [comment]
When I made some contributions to royale-docs a week or two ago, I also committed to master because that seemed to have more recent commits than develop. Additionally, the default branch on Github is currently master and not develop, unlike the other royale repositories that default to develop. Finally, the contents of the master branch is also what appears on the live royale-docs website.

**Comment by piotrzarzycki21** [comment]
@Aszusz let's continue improvements towards master - if anyone would like to change something - we can start discussion on dev.

**Comment by carlosrovira** [comment]
Hi Guys, getting to this now, was very busy this days with other things, seem I don't have to do nothing for now. Let me know in case I'm wrong. Thanks!

**Pull request merged**
